name: CI + Deploy + Jira

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Giả lập deployment (không cần domain thật)
      - name: Create GitHub Deployment
        uses: marvinpinto/action-deployment@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: staging
          ref: ${{ github.ref }}

      - name: Set Deployment Status to Success
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success

      # Gửi thông tin deployment lên Jira
      - name: Notify Jira of deployment
        uses: atlassian/gajira-deploy@v3
        with:
          site: ${{ secrets.JIRA_CLOUD_URL }}
          email: ${{ secrets.JIRA_SITE }}
          apiToken: ${{ secrets.JIRA_API_TOKEN }}
          environment: staging
          state: successful
          issueSummary: "Deployed staging environment"
